### ISSUE TITLE
Some syntax errors in tutorials

### ISSUE THREAD

**Issue by bringuiers** [FluxML/fluxml.github.io#112]
I'm working through some of the tutorials and finding some syntax issues, for example in the [multilayer perception](https://github.com/FluxML/fluxml.github.io/blob/main/tutorials/_posts/2021-01-26-mlp.md)  on lines 62-63

```julia
function getdata(args)
    ...
    # Batching
    train_data = DataLoader(xtrain, ytrain, batchsize=args.batchsize, shuffle=true)
    test_data = DataLoader(xtest, ytest, batchsize=args.batchsize)
    ...
end
```
will throw a method error since `DataLoader` expects the first argument to be `zip(xtrain,ytrain)`

I think there are some other minor syntax issues as well.

**Comment by ToucheSir** [comment]
This was fixed in https://github.com/FluxML/model-zoo/pull/325, but the tutorial wasn't updated to match. Do you mind filing a PR?

Longer term, we should look into having the two sync so that every fix doesn't require changes in 2 repos.

**Comment by logankilpatrick** [comment]
@ToucheSir I think we are going to have @lilianabs working on this

**Comment by ToucheSir** [comment]
Fixed in https://github.com/FluxML/fluxml.github.io/pull/113, thanks @bringuiers!
