### ISSUE TITLE
getting started webpage error

### ISSUE THREAD

**Issue by luigiannelli** [FluxML/fluxml.github.io#132]
in the [getting started page](https://fluxml.ai/getting_started.html) the command `ps = params(W, b)` returns
```
ERROR: UndefVarError: params not defined
Stacktrace:
 [1] top-level scope
   @ REPL[17]:1
 [2] top-level scope
   @ ~/.julia/packages/CUDA/GGwVa/src/initialization.jl:52
```
while `ps = Flux.params(W, b)` works correctly.
maybe fix the getting started page.

**Comment by ToucheSir** [comment]
Looks like a quick change, care to drop a PR?
