### ISSUE TITLE
Switch site to use Franklin

### ISSUE THREAD

**Issue by logankilpatrick** [FluxML/fluxml.github.io#136]
Hey @darsnack we already started the transition to Flux: https://github.com/tlienart/fluxml-franklin I have somewhat dropped the ball on this but can pick it back up if it's a high priority item. Very busy with too many things these days : )

**Comment by darsnack** [comment]
This is great, thank you! If you are too busy, I don't mind picking up the torch and finishing this up.

**Comment by logankilpatrick** [comment]
I would be happy to hand this off, I'm still playing catch up and will be away for most of Sept on travel.

**Comment by mcabbott** [comment]
A perhaps related question, if changing things up: Can we make the documentation more part of the website? While it's on the same domain, https://fluxml.ai/Flux.jl/dev/ is its own universe, with no way back to the rest of the website. It's confusing to know where to look for pages like  https://fluxml.ai/getting_started.html , which is a lot like https://fluxml.ai/Flux.jl/dev/models/overview/ ...

Content aside, I guess my question here is what has to happen to have the top bar of the website shown on the documenter-generated docs pages? 

This is done by e.g. https://turing.ml/v0.21/docs/using-turing/, it seems they use jekyll ([here](https://github.com/TuringLang/turing.ml#building-the-documentation-site-locally)) but surely this can be done with any engine.

**Comment by darsnack** [comment]
My long term plan would be to remove all the tutorials, getting started, etc. in favor of documentation. Similarly, I would like to get rid of the model-zoo and move each example into the docs as tutorials.

Making it look nice (i.e. having a consistent top bar) would be nice too. I haven't looked into whether that's possible.
