### ISSUE TITLE
MNIST experiment accuracy 

### ISSUE THREAD

**Issue by mcognetta** [FluxML/fluxml.github.io#28]
The accuracy of the conv classifier for MNIST on the website is rather poor. This is because the model was trained for only one epoch (if the code from model-zoo) was actually used. 

See: https://github.com/FluxML/model-zoo/pull/72.

I have weights for a model in bson format that I can make a PR for if necessary.

**Comment by MikeInnes** [comment]
Worth talking to @Roboneet. I'm not sure what the specs of the model are at this point; for a while it seemed to be working much better.

**Comment by Roboneet** [comment]
The current model has an accuracy of approx 96% on the dataset (iirc). Also, the first layer of the model used a size of (3, 3) (instead of (2, 2) as in model-zoo), because of an issue with the javascript layers (This may not come up in newer versions of tf-js). It'd be nice to have a better model :)

**Comment by mcognetta** [comment]
@Roboneet Thanks for the info. I figured it used the weights that would result from the linked example on model zoo. Have you tried it out on the website recently? I don't think it is as accurate as advertised.

**Comment by Roboneet** [comment]
@mcognetta, you can try the model using [this](https://github.com/Roboneet/fluxml.github.io/blob/e03d7283b4f735fc5588fb8e317022ae8c7cdee9/experiments/mnist/assets/bson/mnist-conv-model.bson) (use Flux.jl#5d8b63d commit)

**Comment by ToucheSir** [comment]
Since the experiments have long since become unmaintained and moved into the attic, I'm going to close this up. We can always re-open if/when the experiments are rejuvenated.
