### ISSUE TITLE
Mobile/compact navigation menu broken

### ISSUE THREAD

**Issue by amellnik** [FluxML/fluxml.github.io#3]
For browser windows below 992px in width the top navigation bar collapses into a mobile-style dropdown.  When I click on it in either Chrome or Firefox (mobile or desktop) it animates open but then collapses again as soon as the animation finishes.

**Comment by MikeInnes** [comment]
Any suggestions on why this might be happening? I see it to but didn't think I'd made any changes to the basic bootstrap template, so I guess it'll take some debugging.
