### ISSUE TITLE
Require 2FA for all members of the FluxML organization?

### ISSUE THREAD

**Issue by DilumAluthge** [FluxML/fluxml.github.io#46]
https://discourse.julialang.org/t/enabling-2fa-on-major-github-orgs/31957

What do you think about requiring 2FA for all members of the FluxML GitHub organization?

cc: @MikeInnes @ViralBShah

**Comment by ViralBShah** [comment]
The following folks who are in the org need to enable 2FA before we can require 2FA:

@jessebett 
@ninjin
@pevnak 
@roberthoenig 
@Roboneet 
@philtomson

**Comment by roberthoenig** [comment]
Done.

**Comment by jessebett** [comment]
Done.

**Comment by pevnak** [comment]
Done as well

**Comment by MikeInnes** [comment]
Looks like this has been enabled now.

**Comment by ViralBShah** [comment]
Those who had not enabled it now have invitations to join back once it is enabled

**Comment by philtomson** [comment]
I just got 2FA enabled. How to get back into FluxML organization?

**Comment by ViralBShah** [comment]
You should have an invitation already.
