### ISSUE TITLE
Update Simple ConvNet tutorial to work with MLDatasets

### ISSUE THREAD

**Issue by ToucheSir** [FluxML/fluxml.github.io#98]
I've got a working version up at https://gist.github.com/ToucheSir/072097e4d50147cdd97dac00c6622317, but don't know if I'll have time to make the necessary site and model zoo (since the original file was removed in https://github.com/FluxML/model-zoo/pull/293) changes any time soon.

cc @lilianabs @CarloLucibello

**Comment by lilianabs** [comment]
@ToucheSir I can add it to the model zoo in a few days.

**Comment by logankilpatrick** [comment]
This should be used to update: https://fluxml.ai/tutorials/2021/02/07/convnet.html right?

**Comment by ToucheSir** [comment]
Done in https://github.com/FluxML/fluxml.github.io/pull/117.
